//---------------------------------------------------------------------------
//    condefs.h - defines needed by Borland C++ Builder console apps 
//---------------------------------------------------------------------------
// $Revision:   1.8  $
//-------------------------------------------------------------------------
//    copyright (c) 1997 Borland International
//----------------------------------------------------------------------------
#ifndef CONDEFS_H
#define CONDEFS_H
//---------------------------------------------------------------------------
#define USEUNIT(ModName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USEOBJ(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USERC(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USEDEF(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USERES(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USELIB(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#define USEFILE(FileName) \
   extern DummyThatIsNeverReferenced
//-----------------------------------------------------------------------
#endif
